import SideBar from '@/components/SideBar'
import './globals.css'


export const metadata = {
  title: 'Upride Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='flex'>
        <SideBar></SideBar>
        {children}
        </div>
      </body>
    </html>
  )
}
